@startuml
title "Registering the User"

actor User
control "UserController" as Controller
control "UserService" as Service
entity UserRepository as Dao
database MongoDB as DB

User -> Controller : /register
Controller -> Service : registerUser(user)
Service -> Dao : save(user)
Dao -> DB
DB --> Dao
Dao --> Service
Service --> Controller
Controller --> User : (200 OK) user

@enduml