@startuml
title <U> Get all available general parking

actor User
control "ParkingController" as Controller
entity ParkingRepository as Dao
database MongoDB as DB

User -> Controller : /listAvailableGeneralSlots
Controller -> Dao : getAvailableGeneralParkingSlots()
Dao -> DB : {'slotBooked':false,\n'slotReserved':false}
DB --> DB
DB --> Dao : List<ParkingSlot>
Dao --> Controller
Controller --> User : (200 OK) List<ParkingSlot>

@enduml